<?php

include('header_includes.php');

$con = mysql_connect('localhost','root','') or die("Could not connect database");
mysql_select_db('es-db', $con) or die("Could not select database");

//############# Lecturer Filter Details Start Here...
if (!empty($_POST['eLecturer']) && empty($_POST['eSubject']) && empty($_POST['eEligibility']) && empty($_POST['eLocation'])) {

	if (empty($_POST['fromdate']) && empty($_POST['todate'])) {
		
		$query = "SELECT * FROM `event` WHERE electurer = '".$_POST['eLecturer']."' order by electurer";
		$result = mysql_query($query) or die(mysql_error());$num_row = mysql_num_rows($result);
		if($num_row >=1){echo "<table style='border:1px solid #666;padding:5px;background:#fff'><tr><th style='border:1px solid #666;padding:5px;background:#aaa'>#</th><th style='border:1px solid #666;padding:5px;background:#aaa'>Event</th><th style='border:1px solid #666;padding:5px;background:#aaa'>Lecturer</th><th style='border:1px solid #666;padding:5px;background:#aaa'>Category</th><th style='border:1px solid #666;padding:5px;background:#aaa'>Date</th><th style='border:1px solid #666;padding:5px;background:#aaa'>Time</th><th style='border:1px solid #666;padding:5px;background:#aaa'>Eligibility</th><th style='border:1px solid #666;padding:5px;background:#aaa'>Location</th><th style='border:1px solid #666;padding:5px;background:#aaa'>Venue</th></tr>";while($row = mysql_fetch_array($result)){$lecturer = new Lecturer();$user = new User();$lecturerData = $lecturer->getLecturerName($row['electurer']);$getsubject = $user->getSubjectName($row['ecategory_id']);$geteligibility = $user->getEligibleName($row['eligibility_id']);$getLocation = $user->getLocationName($row['elocation_id']);$getVenue = $user->getVenueName($row['evenue_no']);echo "<tr>";echo "<td style='border:1px solid #666;padding:5px;background:#fff'>".$row['id']."</td>";echo "<td style='border:1px solid #666;padding:5px;background:#fff'>".$row['ename']."</td>";echo "<td style='border:1px solid #666;padding:5px;background:#fff'>".$lecturerData->fname.' '.$lecturerData->lname."</td>";echo "<td style='border:1px solid #666;padding:5px;background:#fff'>".$getsubject->name."</td>";echo "<td style='border:1px solid #666;padding:5px;background:#fff'>".$row['edate']."</td>";echo "<td style='border:1px solid #666;padding:5px;background:#fff'>".$row['ehour'].":".$row['eminute']." ".$row['ehour_to'].":".$row['eminute_to']."</td>";echo "<td style='border:1px solid #666;padding:5px;background:#fff'>".$geteligibility->name."</td>";echo "<td style='border:1px solid #666;padding:5px;background:#fff'>".$getLocation->name."</td>";echo "<td style='border:1px solid #666;padding:5px;background:#fff'>".$getVenue->name."</td>";echo "</tr>";}echo "</table>";}else{echo "No Data.";}
	}
	else{

		$query = "SELECT * FROM `event` WHERE electurer = '".$_POST['eLecturer']."' and edate between '".$_POST['fromdate']."' and '".$_POST['todate']."' order by edate";		
		$result = mysql_query($query) or die(mysql_error());$num_row = mysql_num_rows($result);
		if($num_row >=1){echo "<table style='border:1px solid #666;padding:5px;background:#fff'><tr><th style='border:1px solid #666;padding:5px;background:#aaa'>#</th><th style='border:1px solid #666;padding:5px;background:#aaa'>Event</th><th style='border:1px solid #666;padding:5px;background:#aaa'>Lecturer</th><th style='border:1px solid #666;padding:5px;background:#aaa'>Category</th><th style='border:1px solid #666;padding:5px;background:#aaa'>Date</th><th style='border:1px solid #666;padding:5px;background:#aaa'>Time</th><th style='border:1px solid #666;padding:5px;background:#aaa'>Eligibility</th><th style='border:1px solid #666;padding:5px;background:#aaa'>Location</th><th style='border:1px solid #666;padding:5px;background:#aaa'>Venue</th></tr>";while($row = mysql_fetch_array($result)){$lecturer = new Lecturer();$user = new User();$lecturerData = $lecturer->getLecturerName($row['electurer']);$getsubject = $user->getSubjectName($row['ecategory_id']);$geteligibility = $user->getEligibleName($row['eligibility_id']);$getLocation = $user->getLocationName($row['elocation_id']);$getVenue = $user->getVenueName($row['evenue_no']);echo "<tr>";echo "<td style='border:1px solid #666;padding:5px;background:#fff'>".$row['id']."</td>";echo "<td style='border:1px solid #666;padding:5px;background:#fff'>".$row['ename']."</td>";echo "<td style='border:1px solid #666;padding:5px;background:#fff'>".$lecturerData->fname.' '.$lecturerData->lname."</td>";echo "<td style='border:1px solid #666;padding:5px;background:#fff'>".$getsubject->name."</td>";echo "<td style='border:1px solid #666;padding:5px;background:#fff'>".$row['edate']."</td>";echo "<td style='border:1px solid #666;padding:5px;background:#fff'>".$row['ehour'].":".$row['eminute']." ".$row['ehour_to'].":".$row['eminute_to']."</td>";echo "<td style='border:1px solid #666;padding:5px;background:#fff'>".$geteligibility->name."</td>";echo "<td style='border:1px solid #666;padding:5px;background:#fff'>".$getLocation->name."</td>";echo "<td style='border:1px solid #666;padding:5px;background:#fff'>".$getVenue->name."</td>";echo "</tr>";}echo "</table>";}else{echo "No Data.";}
	}	
}

//############# Subject Filter Details Start Here...
if (empty($_POST['eLecturer']) && !empty($_POST['eSubject']) && empty($_POST['eEligibility']) && empty($_POST['eLocation'])) {

	if (empty($_POST['fromdate']) && empty($_POST['todate'])) {

		$query = "SELECT * FROM `event` WHERE ecategory_id = '".$_POST['eSubject']."' order by ecategory_id";
		$result = mysql_query($query) or die(mysql_error());$num_row = mysql_num_rows($result);
		if($num_row >=1){echo "<table style='border:1px solid #666;padding:5px;background:#fff'><tr><th style='border:1px solid #666;padding:5px;background:#aaa'>#</th><th style='border:1px solid #666;padding:5px;background:#aaa'>Event</th><th style='border:1px solid #666;padding:5px;background:#aaa'>Lecturer</th><th style='border:1px solid #666;padding:5px;background:#aaa'>Category</th><th style='border:1px solid #666;padding:5px;background:#aaa'>Date</th><th style='border:1px solid #666;padding:5px;background:#aaa'>Time</th><th style='border:1px solid #666;padding:5px;background:#aaa'>Eligibility</th><th style='border:1px solid #666;padding:5px;background:#aaa'>Location</th><th style='border:1px solid #666;padding:5px;background:#aaa'>Venue</th></tr>";while($row = mysql_fetch_array($result)){$lecturer = new Lecturer();$user = new User();$lecturerData = $lecturer->getLecturerName($row['electurer']);$getsubject = $user->getSubjectName($row['ecategory_id']);$geteligibility = $user->getEligibleName($row['eligibility_id']);$getLocation = $user->getLocationName($row['elocation_id']);$getVenue = $user->getVenueName($row['evenue_no']);echo "<tr>";echo "<td style='border:1px solid #666;padding:5px;background:#fff'>".$row['id']."</td>";echo "<td style='border:1px solid #666;padding:5px;background:#fff'>".$row['ename']."</td>";echo "<td style='border:1px solid #666;padding:5px;background:#fff'>".$lecturerData->fname.' '.$lecturerData->lname."</td>";echo "<td style='border:1px solid #666;padding:5px;background:#fff'>".$getsubject->name."</td>";echo "<td style='border:1px solid #666;padding:5px;background:#fff'>".$row['edate']."</td>";echo "<td style='border:1px solid #666;padding:5px;background:#fff'>".$row['ehour'].":".$row['eminute']." ".$row['ehour_to'].":".$row['eminute_to']."</td>";echo "<td style='border:1px solid #666;padding:5px;background:#fff'>".$geteligibility->name."</td>";echo "<td style='border:1px solid #666;padding:5px;background:#fff'>".$getLocation->name."</td>";echo "<td style='border:1px solid #666;padding:5px;background:#fff'>".$getVenue->name."</td>";echo "</tr>";}echo "</table>";}else{echo "No Data.";}
	}
	else{

		$query = "SELECT * FROM `event` WHERE ecategory_id = '".$_POST['eSubject']."' and edate between '".$_POST['fromdate']."' and '".$_POST['todate']."' order by edate";		
		$result = mysql_query($query) or die(mysql_error());$num_row = mysql_num_rows($result);
		if($num_row >=1){echo "<table style='border:1px solid #666;padding:5px;background:#fff'><tr><th style='border:1px solid #666;padding:5px;background:#aaa'>#</th><th style='border:1px solid #666;padding:5px;background:#aaa'>Event</th><th style='border:1px solid #666;padding:5px;background:#aaa'>Lecturer</th><th style='border:1px solid #666;padding:5px;background:#aaa'>Category</th><th style='border:1px solid #666;padding:5px;background:#aaa'>Date</th><th style='border:1px solid #666;padding:5px;background:#aaa'>Time</th><th style='border:1px solid #666;padding:5px;background:#aaa'>Eligibility</th><th style='border:1px solid #666;padding:5px;background:#aaa'>Location</th><th style='border:1px solid #666;padding:5px;background:#aaa'>Venue</th></tr>";while($row = mysql_fetch_array($result)){$lecturer = new Lecturer();$user = new User();$lecturerData = $lecturer->getLecturerName($row['electurer']);$getsubject = $user->getSubjectName($row['ecategory_id']);$geteligibility = $user->getEligibleName($row['eligibility_id']);$getLocation = $user->getLocationName($row['elocation_id']);$getVenue = $user->getVenueName($row['evenue_no']);echo "<tr>";echo "<td style='border:1px solid #666;padding:5px;background:#fff'>".$row['id']."</td>";echo "<td style='border:1px solid #666;padding:5px;background:#fff'>".$row['ename']."</td>";echo "<td style='border:1px solid #666;padding:5px;background:#fff'>".$lecturerData->fname.' '.$lecturerData->lname."</td>";echo "<td style='border:1px solid #666;padding:5px;background:#fff'>".$getsubject->name."</td>";echo "<td style='border:1px solid #666;padding:5px;background:#fff'>".$row['edate']."</td>";echo "<td style='border:1px solid #666;padding:5px;background:#fff'>".$row['ehour'].":".$row['eminute']." ".$row['ehour_to'].":".$row['eminute_to']."</td>";echo "<td style='border:1px solid #666;padding:5px;background:#fff'>".$geteligibility->name."</td>";echo "<td style='border:1px solid #666;padding:5px;background:#fff'>".$getLocation->name."</td>";echo "<td style='border:1px solid #666;padding:5px;background:#fff'>".$getVenue->name."</td>";echo "</tr>";}echo "</table>";}else{echo "No Data.";}
	}	
}

//############# Eligibility Filter Details Start Here...
if (empty($_POST['eLecturer']) && empty($_POST['eSubject']) && !empty($_POST['eEligibility']) && empty($_POST['eLocation'])) {

	if (empty($_POST['fromdate']) && empty($_POST['todate'])) {
		
		$query = "SELECT * FROM `event` WHERE eligibility_id = '".$_POST['eEligibility']."' order by eligibility_id";
		$result = mysql_query($query) or die(mysql_error());$num_row = mysql_num_rows($result);
		if($num_row >=1){echo "<table style='border:1px solid #666;padding:5px;background:#fff'><tr><th style='border:1px solid #666;padding:5px;background:#aaa'>#</th><th style='border:1px solid #666;padding:5px;background:#aaa'>Event</th><th style='border:1px solid #666;padding:5px;background:#aaa'>Lecturer</th><th style='border:1px solid #666;padding:5px;background:#aaa'>Category</th><th style='border:1px solid #666;padding:5px;background:#aaa'>Date</th><th style='border:1px solid #666;padding:5px;background:#aaa'>Time</th><th style='border:1px solid #666;padding:5px;background:#aaa'>Eligibility</th><th style='border:1px solid #666;padding:5px;background:#aaa'>Location</th><th style='border:1px solid #666;padding:5px;background:#aaa'>Venue</th></tr>";while($row = mysql_fetch_array($result)){$lecturer = new Lecturer();$user = new User();$lecturerData = $lecturer->getLecturerName($row['electurer']);$getsubject = $user->getSubjectName($row['ecategory_id']);$geteligibility = $user->getEligibleName($row['eligibility_id']);$getLocation = $user->getLocationName($row['elocation_id']);$getVenue = $user->getVenueName($row['evenue_no']);echo "<tr>";echo "<td style='border:1px solid #666;padding:5px;background:#fff'>".$row['id']."</td>";echo "<td style='border:1px solid #666;padding:5px;background:#fff'>".$row['ename']."</td>";echo "<td style='border:1px solid #666;padding:5px;background:#fff'>".$lecturerData->fname.' '.$lecturerData->lname."</td>";echo "<td style='border:1px solid #666;padding:5px;background:#fff'>".$getsubject->name."</td>";echo "<td style='border:1px solid #666;padding:5px;background:#fff'>".$row['edate']."</td>";echo "<td style='border:1px solid #666;padding:5px;background:#fff'>".$row['ehour'].":".$row['eminute']." ".$row['ehour_to'].":".$row['eminute_to']."</td>";echo "<td style='border:1px solid #666;padding:5px;background:#fff'>".$geteligibility->name."</td>";echo "<td style='border:1px solid #666;padding:5px;background:#fff'>".$getLocation->name."</td>";echo "<td style='border:1px solid #666;padding:5px;background:#fff'>".$getVenue->name."</td>";echo "</tr>";}echo "</table>";}else{echo "No Data.";}
	}
	else{

		$query = "SELECT * FROM `event` WHERE eligibility_id = '".$_POST['eEligibility']."' and edate between '".$_POST['fromdate']."' and '".$_POST['todate']."' order by edate";		
		$result = mysql_query($query) or die(mysql_error());$num_row = mysql_num_rows($result);
		if($num_row >=1){echo "<table style='border:1px solid #666;padding:5px;background:#fff'><tr><th style='border:1px solid #666;padding:5px;background:#aaa'>#</th><th style='border:1px solid #666;padding:5px;background:#aaa'>Event</th><th style='border:1px solid #666;padding:5px;background:#aaa'>Lecturer</th><th style='border:1px solid #666;padding:5px;background:#aaa'>Category</th><th style='border:1px solid #666;padding:5px;background:#aaa'>Date</th><th style='border:1px solid #666;padding:5px;background:#aaa'>Time</th><th style='border:1px solid #666;padding:5px;background:#aaa'>Eligibility</th><th style='border:1px solid #666;padding:5px;background:#aaa'>Location</th><th style='border:1px solid #666;padding:5px;background:#aaa'>Venue</th></tr>";while($row = mysql_fetch_array($result)){$lecturer = new Lecturer();$user = new User();$lecturerData = $lecturer->getLecturerName($row['electurer']);$getsubject = $user->getSubjectName($row['ecategory_id']);$geteligibility = $user->getEligibleName($row['eligibility_id']);$getLocation = $user->getLocationName($row['elocation_id']);$getVenue = $user->getVenueName($row['evenue_no']);echo "<tr>";echo "<td style='border:1px solid #666;padding:5px;background:#fff'>".$row['id']."</td>";echo "<td style='border:1px solid #666;padding:5px;background:#fff'>".$row['ename']."</td>";echo "<td style='border:1px solid #666;padding:5px;background:#fff'>".$lecturerData->fname.' '.$lecturerData->lname."</td>";echo "<td style='border:1px solid #666;padding:5px;background:#fff'>".$getsubject->name."</td>";echo "<td style='border:1px solid #666;padding:5px;background:#fff'>".$row['edate']."</td>";echo "<td style='border:1px solid #666;padding:5px;background:#fff'>".$row['ehour'].":".$row['eminute']." ".$row['ehour_to'].":".$row['eminute_to']."</td>";echo "<td style='border:1px solid #666;padding:5px;background:#fff'>".$geteligibility->name."</td>";echo "<td style='border:1px solid #666;padding:5px;background:#fff'>".$getLocation->name."</td>";echo "<td style='border:1px solid #666;padding:5px;background:#fff'>".$getVenue->name."</td>";echo "</tr>";}echo "</table>";}else{echo "No Data.";}
	}	
}

//############# Location Filter Details Start Here...
if (empty($_POST['eLecturer']) && empty($_POST['eSubject']) && empty($_POST['eEligibility']) && !empty($_POST['eLocation'])) {

	if (empty($_POST['fromdate']) && empty($_POST['todate'])) {
		
		$query = "SELECT * FROM `event` WHERE elocation_id = '".$_POST['eLocation']."' order by elocation_id";
		$result = mysql_query($query) or die(mysql_error());$num_row = mysql_num_rows($result);
		if($num_row >=1){echo "<table style='border:1px solid #666;padding:5px;background:#fff'><tr><th style='border:1px solid #666;padding:5px;background:#aaa'>#</th><th style='border:1px solid #666;padding:5px;background:#aaa'>Event</th><th style='border:1px solid #666;padding:5px;background:#aaa'>Lecturer</th><th style='border:1px solid #666;padding:5px;background:#aaa'>Category</th><th style='border:1px solid #666;padding:5px;background:#aaa'>Date</th><th style='border:1px solid #666;padding:5px;background:#aaa'>Time</th><th style='border:1px solid #666;padding:5px;background:#aaa'>Eligibility</th><th style='border:1px solid #666;padding:5px;background:#aaa'>Location</th><th style='border:1px solid #666;padding:5px;background:#aaa'>Venue</th></tr>";while($row = mysql_fetch_array($result)){$lecturer = new Lecturer();$user = new User();$lecturerData = $lecturer->getLecturerName($row['electurer']);$getsubject = $user->getSubjectName($row['ecategory_id']);$geteligibility = $user->getEligibleName($row['eligibility_id']);$getLocation = $user->getLocationName($row['elocation_id']);$getVenue = $user->getVenueName($row['evenue_no']);echo "<tr>";echo "<td style='border:1px solid #666;padding:5px;background:#fff'>".$row['id']."</td>";echo "<td style='border:1px solid #666;padding:5px;background:#fff'>".$row['ename']."</td>";echo "<td style='border:1px solid #666;padding:5px;background:#fff'>".$lecturerData->fname.' '.$lecturerData->lname."</td>";echo "<td style='border:1px solid #666;padding:5px;background:#fff'>".$getsubject->name."</td>";echo "<td style='border:1px solid #666;padding:5px;background:#fff'>".$row['edate']."</td>";echo "<td style='border:1px solid #666;padding:5px;background:#fff'>".$row['ehour'].":".$row['eminute']." ".$row['ehour_to'].":".$row['eminute_to']."</td>";echo "<td style='border:1px solid #666;padding:5px;background:#fff'>".$geteligibility->name."</td>";echo "<td style='border:1px solid #666;padding:5px;background:#fff'>".$getLocation->name."</td>";echo "<td style='border:1px solid #666;padding:5px;background:#fff'>".$getVenue->name."</td>";echo "</tr>";}echo "</table>";}else{echo "No Data.";}
	}
	else{

		$query = "SELECT * FROM `event` WHERE elocation_id = '".$_POST['eLocation']."' and edate between '".$_POST['fromdate']."' and '".$_POST['todate']."' order by edate";		
		$result = mysql_query($query) or die(mysql_error());$num_row = mysql_num_rows($result);
		if($num_row >=1){echo "<table style='border:1px solid #666;padding:5px;background:#fff'><tr><th style='border:1px solid #666;padding:5px;background:#aaa'>#</th><th style='border:1px solid #666;padding:5px;background:#aaa'>Event</th><th style='border:1px solid #666;padding:5px;background:#aaa'>Lecturer</th><th style='border:1px solid #666;padding:5px;background:#aaa'>Category</th><th style='border:1px solid #666;padding:5px;background:#aaa'>Date</th><th style='border:1px solid #666;padding:5px;background:#aaa'>Time</th><th style='border:1px solid #666;padding:5px;background:#aaa'>Eligibility</th><th style='border:1px solid #666;padding:5px;background:#aaa'>Location</th><th style='border:1px solid #666;padding:5px;background:#aaa'>Venue</th></tr>";while($row = mysql_fetch_array($result)){$lecturer = new Lecturer();$user = new User();$lecturerData = $lecturer->getLecturerName($row['electurer']);$getsubject = $user->getSubjectName($row['ecategory_id']);$geteligibility = $user->getEligibleName($row['eligibility_id']);$getLocation = $user->getLocationName($row['elocation_id']);$getVenue = $user->getVenueName($row['evenue_no']);echo "<tr>";echo "<td style='border:1px solid #666;padding:5px;background:#fff'>".$row['id']."</td>";echo "<td style='border:1px solid #666;padding:5px;background:#fff'>".$row['ename']."</td>";echo "<td style='border:1px solid #666;padding:5px;background:#fff'>".$lecturerData->fname.' '.$lecturerData->lname."</td>";echo "<td style='border:1px solid #666;padding:5px;background:#fff'>".$getsubject->name."</td>";echo "<td style='border:1px solid #666;padding:5px;background:#fff'>".$row['edate']."</td>";echo "<td style='border:1px solid #666;padding:5px;background:#fff'>".$row['ehour'].":".$row['eminute']." ".$row['ehour_to'].":".$row['eminute_to']."</td>";echo "<td style='border:1px solid #666;padding:5px;background:#fff'>".$geteligibility->name."</td>";echo "<td style='border:1px solid #666;padding:5px;background:#fff'>".$getLocation->name."</td>";echo "<td style='border:1px solid #666;padding:5px;background:#fff'>".$getVenue->name."</td>";echo "</tr>";}echo "</table>";}else{echo "No Data.";}
	}	
}

//############# Lecturer & Subject Filter Details Start Here...
if (!empty($_POST['eLecturer']) && !empty($_POST['eSubject']) && empty($_POST['eEligibility']) && empty($_POST['eLocation'])) {

	if (empty($_POST['fromdate']) && empty($_POST['todate'])) {
		
		$query = "SELECT * FROM `event` WHERE electurer = '".$_POST['eLecturer']."' and ecategory_id = '".$_POST['eSubject']."' order by electurer";
		$result = mysql_query($query) or die(mysql_error());$num_row = mysql_num_rows($result);
		if($num_row >=1){echo "<table style='border:1px solid #666;padding:5px;background:#fff'><tr><th style='border:1px solid #666;padding:5px;background:#aaa'>#</th><th style='border:1px solid #666;padding:5px;background:#aaa'>Event</th><th style='border:1px solid #666;padding:5px;background:#aaa'>Lecturer</th><th style='border:1px solid #666;padding:5px;background:#aaa'>Category</th><th style='border:1px solid #666;padding:5px;background:#aaa'>Date</th><th style='border:1px solid #666;padding:5px;background:#aaa'>Time</th><th style='border:1px solid #666;padding:5px;background:#aaa'>Eligibility</th><th style='border:1px solid #666;padding:5px;background:#aaa'>Location</th><th style='border:1px solid #666;padding:5px;background:#aaa'>Venue</th></tr>";while($row = mysql_fetch_array($result)){$lecturer = new Lecturer();$user = new User();$lecturerData = $lecturer->getLecturerName($row['electurer']);$getsubject = $user->getSubjectName($row['ecategory_id']);$geteligibility = $user->getEligibleName($row['eligibility_id']);$getLocation = $user->getLocationName($row['elocation_id']);$getVenue = $user->getVenueName($row['evenue_no']);echo "<tr>";echo "<td style='border:1px solid #666;padding:5px;background:#fff'>".$row['id']."</td>";echo "<td style='border:1px solid #666;padding:5px;background:#fff'>".$row['ename']."</td>";echo "<td style='border:1px solid #666;padding:5px;background:#fff'>".$lecturerData->fname.' '.$lecturerData->lname."</td>";echo "<td style='border:1px solid #666;padding:5px;background:#fff'>".$getsubject->name."</td>";echo "<td style='border:1px solid #666;padding:5px;background:#fff'>".$row['edate']."</td>";echo "<td style='border:1px solid #666;padding:5px;background:#fff'>".$row['ehour'].":".$row['eminute']." ".$row['ehour_to'].":".$row['eminute_to']."</td>";echo "<td style='border:1px solid #666;padding:5px;background:#fff'>".$geteligibility->name."</td>";echo "<td style='border:1px solid #666;padding:5px;background:#fff'>".$getLocation->name."</td>";echo "<td style='border:1px solid #666;padding:5px;background:#fff'>".$getVenue->name."</td>";echo "</tr>";}echo "</table>";}else{echo "No Data.";}
	}
	else{

		$query = "SELECT * FROM `event` WHERE electurer = '".$_POST['eLecturer']."' and ecategory_id = '".$_POST['eSubject']."' and edate between '".$_POST['fromdate']."' and '".$_POST['todate']."' order by edate";		
		$result = mysql_query($query) or die(mysql_error());$num_row = mysql_num_rows($result);
		if($num_row >=1){echo "<table style='border:1px solid #666;padding:5px;background:#fff'><tr><th style='border:1px solid #666;padding:5px;background:#aaa'>#</th><th style='border:1px solid #666;padding:5px;background:#aaa'>Event</th><th style='border:1px solid #666;padding:5px;background:#aaa'>Lecturer</th><th style='border:1px solid #666;padding:5px;background:#aaa'>Category</th><th style='border:1px solid #666;padding:5px;background:#aaa'>Date</th><th style='border:1px solid #666;padding:5px;background:#aaa'>Time</th><th style='border:1px solid #666;padding:5px;background:#aaa'>Eligibility</th><th style='border:1px solid #666;padding:5px;background:#aaa'>Location</th><th style='border:1px solid #666;padding:5px;background:#aaa'>Venue</th></tr>";while($row = mysql_fetch_array($result)){$lecturer = new Lecturer();$user = new User();$lecturerData = $lecturer->getLecturerName($row['electurer']);$getsubject = $user->getSubjectName($row['ecategory_id']);$geteligibility = $user->getEligibleName($row['eligibility_id']);$getLocation = $user->getLocationName($row['elocation_id']);$getVenue = $user->getVenueName($row['evenue_no']);echo "<tr>";echo "<td style='border:1px solid #666;padding:5px;background:#fff'>".$row['id']."</td>";echo "<td style='border:1px solid #666;padding:5px;background:#fff'>".$row['ename']."</td>";echo "<td style='border:1px solid #666;padding:5px;background:#fff'>".$lecturerData->fname.' '.$lecturerData->lname."</td>";echo "<td style='border:1px solid #666;padding:5px;background:#fff'>".$getsubject->name."</td>";echo "<td style='border:1px solid #666;padding:5px;background:#fff'>".$row['edate']."</td>";echo "<td style='border:1px solid #666;padding:5px;background:#fff'>".$row['ehour'].":".$row['eminute']." ".$row['ehour_to'].":".$row['eminute_to']."</td>";echo "<td style='border:1px solid #666;padding:5px;background:#fff'>".$geteligibility->name."</td>";echo "<td style='border:1px solid #666;padding:5px;background:#fff'>".$getLocation->name."</td>";echo "<td style='border:1px solid #666;padding:5px;background:#fff'>".$getVenue->name."</td>";echo "</tr>";}echo "</table>";}else{echo "No Data.";}
	}	
}

//############# Lecturer & Eligibility Filter Details Start Here...
if (!empty($_POST['eLecturer']) && empty($_POST['eSubject']) && !empty($_POST['eEligibility']) && empty($_POST['eLocation'])) {

	if (empty($_POST['fromdate']) && empty($_POST['todate'])) {
		
		$query = "SELECT * FROM `event` WHERE electurer = '".$_POST['eLecturer']."' and eligibility_id = '".$_POST['eEligibility']."' order by electurer";
		$result = mysql_query($query) or die(mysql_error());$num_row = mysql_num_rows($result);
		if($num_row >=1){echo "<table style='border:1px solid #666;padding:5px;background:#fff'><tr><th style='border:1px solid #666;padding:5px;background:#aaa'>#</th><th style='border:1px solid #666;padding:5px;background:#aaa'>Event</th><th style='border:1px solid #666;padding:5px;background:#aaa'>Lecturer</th><th style='border:1px solid #666;padding:5px;background:#aaa'>Category</th><th style='border:1px solid #666;padding:5px;background:#aaa'>Date</th><th style='border:1px solid #666;padding:5px;background:#aaa'>Time</th><th style='border:1px solid #666;padding:5px;background:#aaa'>Eligibility</th><th style='border:1px solid #666;padding:5px;background:#aaa'>Location</th><th style='border:1px solid #666;padding:5px;background:#aaa'>Venue</th></tr>";while($row = mysql_fetch_array($result)){$lecturer = new Lecturer();$user = new User();$lecturerData = $lecturer->getLecturerName($row['electurer']);$getsubject = $user->getSubjectName($row['ecategory_id']);$geteligibility = $user->getEligibleName($row['eligibility_id']);$getLocation = $user->getLocationName($row['elocation_id']);$getVenue = $user->getVenueName($row['evenue_no']);echo "<tr>";echo "<td style='border:1px solid #666;padding:5px;background:#fff'>".$row['id']."</td>";echo "<td style='border:1px solid #666;padding:5px;background:#fff'>".$row['ename']."</td>";echo "<td style='border:1px solid #666;padding:5px;background:#fff'>".$lecturerData->fname.' '.$lecturerData->lname."</td>";echo "<td style='border:1px solid #666;padding:5px;background:#fff'>".$getsubject->name."</td>";echo "<td style='border:1px solid #666;padding:5px;background:#fff'>".$row['edate']."</td>";echo "<td style='border:1px solid #666;padding:5px;background:#fff'>".$row['ehour'].":".$row['eminute']." ".$row['ehour_to'].":".$row['eminute_to']."</td>";echo "<td style='border:1px solid #666;padding:5px;background:#fff'>".$geteligibility->name."</td>";echo "<td style='border:1px solid #666;padding:5px;background:#fff'>".$getLocation->name."</td>";echo "<td style='border:1px solid #666;padding:5px;background:#fff'>".$getVenue->name."</td>";echo "</tr>";}echo "</table>";}else{echo "No Data.";}
	}
	else{

		$query = "SELECT * FROM `event` WHERE electurer = '".$_POST['eLecturer']."' and eligibility_id = '".$_POST['eEligibility']."' and edate between '".$_POST['fromdate']."' and '".$_POST['todate']."' order by edate";		
		$result = mysql_query($query) or die(mysql_error());$num_row = mysql_num_rows($result);
		if($num_row >=1){echo "<table style='border:1px solid #666;padding:5px;background:#fff'><tr><th style='border:1px solid #666;padding:5px;background:#aaa'>#</th><th style='border:1px solid #666;padding:5px;background:#aaa'>Event</th><th style='border:1px solid #666;padding:5px;background:#aaa'>Lecturer</th><th style='border:1px solid #666;padding:5px;background:#aaa'>Category</th><th style='border:1px solid #666;padding:5px;background:#aaa'>Date</th><th style='border:1px solid #666;padding:5px;background:#aaa'>Time</th><th style='border:1px solid #666;padding:5px;background:#aaa'>Eligibility</th><th style='border:1px solid #666;padding:5px;background:#aaa'>Location</th><th style='border:1px solid #666;padding:5px;background:#aaa'>Venue</th></tr>";while($row = mysql_fetch_array($result)){$lecturer = new Lecturer();$user = new User();$lecturerData = $lecturer->getLecturerName($row['electurer']);$getsubject = $user->getSubjectName($row['ecategory_id']);$geteligibility = $user->getEligibleName($row['eligibility_id']);$getLocation = $user->getLocationName($row['elocation_id']);$getVenue = $user->getVenueName($row['evenue_no']);echo "<tr>";echo "<td style='border:1px solid #666;padding:5px;background:#fff'>".$row['id']."</td>";echo "<td style='border:1px solid #666;padding:5px;background:#fff'>".$row['ename']."</td>";echo "<td style='border:1px solid #666;padding:5px;background:#fff'>".$lecturerData->fname.' '.$lecturerData->lname."</td>";echo "<td style='border:1px solid #666;padding:5px;background:#fff'>".$getsubject->name."</td>";echo "<td style='border:1px solid #666;padding:5px;background:#fff'>".$row['edate']."</td>";echo "<td style='border:1px solid #666;padding:5px;background:#fff'>".$row['ehour'].":".$row['eminute']." ".$row['ehour_to'].":".$row['eminute_to']."</td>";echo "<td style='border:1px solid #666;padding:5px;background:#fff'>".$geteligibility->name."</td>";echo "<td style='border:1px solid #666;padding:5px;background:#fff'>".$getLocation->name."</td>";echo "<td style='border:1px solid #666;padding:5px;background:#fff'>".$getVenue->name."</td>";echo "</tr>";}echo "</table>";}else{echo "No Data.";}
	}	
}

//############# Lecturer & Location Filter Details Start Here...
if (!empty($_POST['eLecturer']) && empty($_POST['eSubject']) && empty($_POST['eEligibility']) && !empty($_POST['eLocation'])) {

	if (empty($_POST['fromdate']) && empty($_POST['todate'])) {
		
		$query = "SELECT * FROM `event` WHERE electurer = '".$_POST['eLecturer']."' and elocation_id = '".$_POST['eLocation']."' order by electurer";
		$result = mysql_query($query) or die(mysql_error());$num_row = mysql_num_rows($result);
		if($num_row >=1){echo "<table style='border:1px solid #666;padding:5px;background:#fff'><tr><th style='border:1px solid #666;padding:5px;background:#aaa'>#</th><th style='border:1px solid #666;padding:5px;background:#aaa'>Event</th><th style='border:1px solid #666;padding:5px;background:#aaa'>Lecturer</th><th style='border:1px solid #666;padding:5px;background:#aaa'>Category</th><th style='border:1px solid #666;padding:5px;background:#aaa'>Date</th><th style='border:1px solid #666;padding:5px;background:#aaa'>Time</th><th style='border:1px solid #666;padding:5px;background:#aaa'>Eligibility</th><th style='border:1px solid #666;padding:5px;background:#aaa'>Location</th><th style='border:1px solid #666;padding:5px;background:#aaa'>Venue</th></tr>";while($row = mysql_fetch_array($result)){$lecturer = new Lecturer();$user = new User();$lecturerData = $lecturer->getLecturerName($row['electurer']);$getsubject = $user->getSubjectName($row['ecategory_id']);$geteligibility = $user->getEligibleName($row['eligibility_id']);$getLocation = $user->getLocationName($row['elocation_id']);$getVenue = $user->getVenueName($row['evenue_no']);echo "<tr>";echo "<td style='border:1px solid #666;padding:5px;background:#fff'>".$row['id']."</td>";echo "<td style='border:1px solid #666;padding:5px;background:#fff'>".$row['ename']."</td>";echo "<td style='border:1px solid #666;padding:5px;background:#fff'>".$lecturerData->fname.' '.$lecturerData->lname."</td>";echo "<td style='border:1px solid #666;padding:5px;background:#fff'>".$getsubject->name."</td>";echo "<td style='border:1px solid #666;padding:5px;background:#fff'>".$row['edate']."</td>";echo "<td style='border:1px solid #666;padding:5px;background:#fff'>".$row['ehour'].":".$row['eminute']." ".$row['ehour_to'].":".$row['eminute_to']."</td>";echo "<td style='border:1px solid #666;padding:5px;background:#fff'>".$geteligibility->name."</td>";echo "<td style='border:1px solid #666;padding:5px;background:#fff'>".$getLocation->name."</td>";echo "<td style='border:1px solid #666;padding:5px;background:#fff'>".$getVenue->name."</td>";echo "</tr>";}echo "</table>";}else{echo "No Data.";}
	}
	else{

		$query = "SELECT * FROM `event` WHERE electurer = '".$_POST['eLecturer']."' and elocation_id = '".$_POST['eLocation']."' and edate between '".$_POST['fromdate']."' and '".$_POST['todate']."' order by edate";		
		$result = mysql_query($query) or die(mysql_error());$num_row = mysql_num_rows($result);
		if($num_row >=1){echo "<table style='border:1px solid #666;padding:5px;background:#fff'><tr><th style='border:1px solid #666;padding:5px;background:#aaa'>#</th><th style='border:1px solid #666;padding:5px;background:#aaa'>Event</th><th style='border:1px solid #666;padding:5px;background:#aaa'>Lecturer</th><th style='border:1px solid #666;padding:5px;background:#aaa'>Category</th><th style='border:1px solid #666;padding:5px;background:#aaa'>Date</th><th style='border:1px solid #666;padding:5px;background:#aaa'>Time</th><th style='border:1px solid #666;padding:5px;background:#aaa'>Eligibility</th><th style='border:1px solid #666;padding:5px;background:#aaa'>Location</th><th style='border:1px solid #666;padding:5px;background:#aaa'>Venue</th></tr>";while($row = mysql_fetch_array($result)){$lecturer = new Lecturer();$user = new User();$lecturerData = $lecturer->getLecturerName($row['electurer']);$getsubject = $user->getSubjectName($row['ecategory_id']);$geteligibility = $user->getEligibleName($row['eligibility_id']);$getLocation = $user->getLocationName($row['elocation_id']);$getVenue = $user->getVenueName($row['evenue_no']);echo "<tr>";echo "<td style='border:1px solid #666;padding:5px;background:#fff'>".$row['id']."</td>";echo "<td style='border:1px solid #666;padding:5px;background:#fff'>".$row['ename']."</td>";echo "<td style='border:1px solid #666;padding:5px;background:#fff'>".$lecturerData->fname.' '.$lecturerData->lname."</td>";echo "<td style='border:1px solid #666;padding:5px;background:#fff'>".$getsubject->name."</td>";echo "<td style='border:1px solid #666;padding:5px;background:#fff'>".$row['edate']."</td>";echo "<td style='border:1px solid #666;padding:5px;background:#fff'>".$row['ehour'].":".$row['eminute']." ".$row['ehour_to'].":".$row['eminute_to']."</td>";echo "<td style='border:1px solid #666;padding:5px;background:#fff'>".$geteligibility->name."</td>";echo "<td style='border:1px solid #666;padding:5px;background:#fff'>".$getLocation->name."</td>";echo "<td style='border:1px solid #666;padding:5px;background:#fff'>".$getVenue->name."</td>";echo "</tr>";}echo "</table>";}else{echo "No Data.";}
	}	
}

//############# Subject & Eligibility Filter Details Start Here...
if (empty($_POST['eLecturer']) && !empty($_POST['eSubject']) && !empty($_POST['eEligibility']) && empty($_POST['eLocation'])) {

	if (empty($_POST['fromdate']) && empty($_POST['todate'])) {
		
		$query = "SELECT * FROM `event` WHERE ecategory_id = '".$_POST['eSubject']."' and eligibility_id = '".$_POST['eEligibility']."' order by electurer";
		$result = mysql_query($query) or die(mysql_error());$num_row = mysql_num_rows($result);
		if($num_row >=1){echo "<table style='border:1px solid #666;padding:5px;background:#fff'><tr><th style='border:1px solid #666;padding:5px;background:#aaa'>#</th><th style='border:1px solid #666;padding:5px;background:#aaa'>Event</th><th style='border:1px solid #666;padding:5px;background:#aaa'>Lecturer</th><th style='border:1px solid #666;padding:5px;background:#aaa'>Category</th><th style='border:1px solid #666;padding:5px;background:#aaa'>Date</th><th style='border:1px solid #666;padding:5px;background:#aaa'>Time</th><th style='border:1px solid #666;padding:5px;background:#aaa'>Eligibility</th><th style='border:1px solid #666;padding:5px;background:#aaa'>Location</th><th style='border:1px solid #666;padding:5px;background:#aaa'>Venue</th></tr>";while($row = mysql_fetch_array($result)){$lecturer = new Lecturer();$user = new User();$lecturerData = $lecturer->getLecturerName($row['electurer']);$getsubject = $user->getSubjectName($row['ecategory_id']);$geteligibility = $user->getEligibleName($row['eligibility_id']);$getLocation = $user->getLocationName($row['elocation_id']);$getVenue = $user->getVenueName($row['evenue_no']);echo "<tr>";echo "<td style='border:1px solid #666;padding:5px;background:#fff'>".$row['id']."</td>";echo "<td style='border:1px solid #666;padding:5px;background:#fff'>".$row['ename']."</td>";echo "<td style='border:1px solid #666;padding:5px;background:#fff'>".$lecturerData->fname.' '.$lecturerData->lname."</td>";echo "<td style='border:1px solid #666;padding:5px;background:#fff'>".$getsubject->name."</td>";echo "<td style='border:1px solid #666;padding:5px;background:#fff'>".$row['edate']."</td>";echo "<td style='border:1px solid #666;padding:5px;background:#fff'>".$row['ehour'].":".$row['eminute']." ".$row['ehour_to'].":".$row['eminute_to']."</td>";echo "<td style='border:1px solid #666;padding:5px;background:#fff'>".$geteligibility->name."</td>";echo "<td style='border:1px solid #666;padding:5px;background:#fff'>".$getLocation->name."</td>";echo "<td style='border:1px solid #666;padding:5px;background:#fff'>".$getVenue->name."</td>";echo "</tr>";}echo "</table>";}else{echo "No Data.";}
	}
	else{

		$query = "SELECT * FROM `event` WHERE ecategory_id = '".$_POST['eSubject']."' and eligibility_id = '".$_POST['eEligibility']."' and edate between '".$_POST['fromdate']."' and '".$_POST['todate']."' order by edate";		
		$result = mysql_query($query) or die(mysql_error());$num_row = mysql_num_rows($result);
		if($num_row >=1){echo "<table style='border:1px solid #666;padding:5px;background:#fff'><tr><th style='border:1px solid #666;padding:5px;background:#aaa'>#</th><th style='border:1px solid #666;padding:5px;background:#aaa'>Event</th><th style='border:1px solid #666;padding:5px;background:#aaa'>Lecturer</th><th style='border:1px solid #666;padding:5px;background:#aaa'>Category</th><th style='border:1px solid #666;padding:5px;background:#aaa'>Date</th><th style='border:1px solid #666;padding:5px;background:#aaa'>Time</th><th style='border:1px solid #666;padding:5px;background:#aaa'>Eligibility</th><th style='border:1px solid #666;padding:5px;background:#aaa'>Location</th><th style='border:1px solid #666;padding:5px;background:#aaa'>Venue</th></tr>";while($row = mysql_fetch_array($result)){$lecturer = new Lecturer();$user = new User();$lecturerData = $lecturer->getLecturerName($row['electurer']);$getsubject = $user->getSubjectName($row['ecategory_id']);$geteligibility = $user->getEligibleName($row['eligibility_id']);$getLocation = $user->getLocationName($row['elocation_id']);$getVenue = $user->getVenueName($row['evenue_no']);echo "<tr>";echo "<td style='border:1px solid #666;padding:5px;background:#fff'>".$row['id']."</td>";echo "<td style='border:1px solid #666;padding:5px;background:#fff'>".$row['ename']."</td>";echo "<td style='border:1px solid #666;padding:5px;background:#fff'>".$lecturerData->fname.' '.$lecturerData->lname."</td>";echo "<td style='border:1px solid #666;padding:5px;background:#fff'>".$getsubject->name."</td>";echo "<td style='border:1px solid #666;padding:5px;background:#fff'>".$row['edate']."</td>";echo "<td style='border:1px solid #666;padding:5px;background:#fff'>".$row['ehour'].":".$row['eminute']." ".$row['ehour_to'].":".$row['eminute_to']."</td>";echo "<td style='border:1px solid #666;padding:5px;background:#fff'>".$geteligibility->name."</td>";echo "<td style='border:1px solid #666;padding:5px;background:#fff'>".$getLocation->name."</td>";echo "<td style='border:1px solid #666;padding:5px;background:#fff'>".$getVenue->name."</td>";echo "</tr>";}echo "</table>";}else{echo "No Data.";}
	}	
}

//############# Subject & Location Filter Details Start Here...
if (empty($_POST['eLecturer']) && !empty($_POST['eSubject']) && empty($_POST['eEligibility']) && !empty($_POST['eLocation'])) {

	if (empty($_POST['fromdate']) && empty($_POST['todate'])) {
		
		$query = "SELECT * FROM `event` WHERE ecategory_id = '".$_POST['eSubject']."' and elocation_id = '".$_POST['eLocation']."' order by electurer";
		$result = mysql_query($query) or die(mysql_error());$num_row = mysql_num_rows($result);
		if($num_row >=1){echo "<table style='border:1px solid #666;padding:5px;background:#fff'><tr><th style='border:1px solid #666;padding:5px;background:#aaa'>#</th><th style='border:1px solid #666;padding:5px;background:#aaa'>Event</th><th style='border:1px solid #666;padding:5px;background:#aaa'>Lecturer</th><th style='border:1px solid #666;padding:5px;background:#aaa'>Category</th><th style='border:1px solid #666;padding:5px;background:#aaa'>Date</th><th style='border:1px solid #666;padding:5px;background:#aaa'>Time</th><th style='border:1px solid #666;padding:5px;background:#aaa'>Eligibility</th><th style='border:1px solid #666;padding:5px;background:#aaa'>Location</th><th style='border:1px solid #666;padding:5px;background:#aaa'>Venue</th></tr>";while($row = mysql_fetch_array($result)){$lecturer = new Lecturer();$user = new User();$lecturerData = $lecturer->getLecturerName($row['electurer']);$getsubject = $user->getSubjectName($row['ecategory_id']);$geteligibility = $user->getEligibleName($row['eligibility_id']);$getLocation = $user->getLocationName($row['elocation_id']);$getVenue = $user->getVenueName($row['evenue_no']);echo "<tr>";echo "<td style='border:1px solid #666;padding:5px;background:#fff'>".$row['id']."</td>";echo "<td style='border:1px solid #666;padding:5px;background:#fff'>".$row['ename']."</td>";echo "<td style='border:1px solid #666;padding:5px;background:#fff'>".$lecturerData->fname.' '.$lecturerData->lname."</td>";echo "<td style='border:1px solid #666;padding:5px;background:#fff'>".$getsubject->name."</td>";echo "<td style='border:1px solid #666;padding:5px;background:#fff'>".$row['edate']."</td>";echo "<td style='border:1px solid #666;padding:5px;background:#fff'>".$row['ehour'].":".$row['eminute']." ".$row['ehour_to'].":".$row['eminute_to']."</td>";echo "<td style='border:1px solid #666;padding:5px;background:#fff'>".$geteligibility->name."</td>";echo "<td style='border:1px solid #666;padding:5px;background:#fff'>".$getLocation->name."</td>";echo "<td style='border:1px solid #666;padding:5px;background:#fff'>".$getVenue->name."</td>";echo "</tr>";}echo "</table>";}else{echo "No Data.";}
	}
	else{

		$query = "SELECT * FROM `event` WHERE ecategory_id = '".$_POST['eSubject']."' and elocation_id = '".$_POST['eLocation']."' and edate between '".$_POST['fromdate']."' and '".$_POST['todate']."' order by edate";		
		$result = mysql_query($query) or die(mysql_error());$num_row = mysql_num_rows($result);
		if($num_row >=1){echo "<table style='border:1px solid #666;padding:5px;background:#fff'><tr><th style='border:1px solid #666;padding:5px;background:#aaa'>#</th><th style='border:1px solid #666;padding:5px;background:#aaa'>Event</th><th style='border:1px solid #666;padding:5px;background:#aaa'>Lecturer</th><th style='border:1px solid #666;padding:5px;background:#aaa'>Category</th><th style='border:1px solid #666;padding:5px;background:#aaa'>Date</th><th style='border:1px solid #666;padding:5px;background:#aaa'>Time</th><th style='border:1px solid #666;padding:5px;background:#aaa'>Eligibility</th><th style='border:1px solid #666;padding:5px;background:#aaa'>Location</th><th style='border:1px solid #666;padding:5px;background:#aaa'>Venue</th></tr>";while($row = mysql_fetch_array($result)){$lecturer = new Lecturer();$user = new User();$lecturerData = $lecturer->getLecturerName($row['electurer']);$getsubject = $user->getSubjectName($row['ecategory_id']);$geteligibility = $user->getEligibleName($row['eligibility_id']);$getLocation = $user->getLocationName($row['elocation_id']);$getVenue = $user->getVenueName($row['evenue_no']);echo "<tr>";echo "<td style='border:1px solid #666;padding:5px;background:#fff'>".$row['id']."</td>";echo "<td style='border:1px solid #666;padding:5px;background:#fff'>".$row['ename']."</td>";echo "<td style='border:1px solid #666;padding:5px;background:#fff'>".$lecturerData->fname.' '.$lecturerData->lname."</td>";echo "<td style='border:1px solid #666;padding:5px;background:#fff'>".$getsubject->name."</td>";echo "<td style='border:1px solid #666;padding:5px;background:#fff'>".$row['edate']."</td>";echo "<td style='border:1px solid #666;padding:5px;background:#fff'>".$row['ehour'].":".$row['eminute']." ".$row['ehour_to'].":".$row['eminute_to']."</td>";echo "<td style='border:1px solid #666;padding:5px;background:#fff'>".$geteligibility->name."</td>";echo "<td style='border:1px solid #666;padding:5px;background:#fff'>".$getLocation->name."</td>";echo "<td style='border:1px solid #666;padding:5px;background:#fff'>".$getVenue->name."</td>";echo "</tr>";}echo "</table>";}else{echo "No Data.";}
	}	
}

//############# Eligibility & Location Filter Details Start Here...
if (empty($_POST['eLecturer']) && empty($_POST['eSubject']) && !empty($_POST['eEligibility']) && !empty($_POST['eLocation'])) {

	if (empty($_POST['fromdate']) && empty($_POST['todate'])) {
		
		$query = "SELECT * FROM `event` WHERE eligibility_id = '".$_POST['eEligibility']."' and elocation_id = '".$_POST['eLocation']."' order by electurer";
		$result = mysql_query($query) or die(mysql_error());$num_row = mysql_num_rows($result);
		if($num_row >=1){echo "<table style='border:1px solid #666;padding:5px;background:#fff'><tr><th style='border:1px solid #666;padding:5px;background:#aaa'>#</th><th style='border:1px solid #666;padding:5px;background:#aaa'>Event</th><th style='border:1px solid #666;padding:5px;background:#aaa'>Lecturer</th><th style='border:1px solid #666;padding:5px;background:#aaa'>Category</th><th style='border:1px solid #666;padding:5px;background:#aaa'>Date</th><th style='border:1px solid #666;padding:5px;background:#aaa'>Time</th><th style='border:1px solid #666;padding:5px;background:#aaa'>Eligibility</th><th style='border:1px solid #666;padding:5px;background:#aaa'>Location</th><th style='border:1px solid #666;padding:5px;background:#aaa'>Venue</th></tr>";while($row = mysql_fetch_array($result)){$lecturer = new Lecturer();$user = new User();$lecturerData = $lecturer->getLecturerName($row['electurer']);$getsubject = $user->getSubjectName($row['ecategory_id']);$geteligibility = $user->getEligibleName($row['eligibility_id']);$getLocation = $user->getLocationName($row['elocation_id']);$getVenue = $user->getVenueName($row['evenue_no']);echo "<tr>";echo "<td style='border:1px solid #666;padding:5px;background:#fff'>".$row['id']."</td>";echo "<td style='border:1px solid #666;padding:5px;background:#fff'>".$row['ename']."</td>";echo "<td style='border:1px solid #666;padding:5px;background:#fff'>".$lecturerData->fname.' '.$lecturerData->lname."</td>";echo "<td style='border:1px solid #666;padding:5px;background:#fff'>".$getsubject->name."</td>";echo "<td style='border:1px solid #666;padding:5px;background:#fff'>".$row['edate']."</td>";echo "<td style='border:1px solid #666;padding:5px;background:#fff'>".$row['ehour'].":".$row['eminute']." ".$row['ehour_to'].":".$row['eminute_to']."</td>";echo "<td style='border:1px solid #666;padding:5px;background:#fff'>".$geteligibility->name."</td>";echo "<td style='border:1px solid #666;padding:5px;background:#fff'>".$getLocation->name."</td>";echo "<td style='border:1px solid #666;padding:5px;background:#fff'>".$getVenue->name."</td>";echo "</tr>";}echo "</table>";}else{echo "No Data.";}
	}
	else{

		$query = "SELECT * FROM `event` WHERE eligibility_id = '".$_POST['eEligibility']."' and elocation_id = '".$_POST['eLocation']."' and edate between '".$_POST['fromdate']."' and '".$_POST['todate']."' order by edate";		
		$result = mysql_query($query) or die(mysql_error());$num_row = mysql_num_rows($result);
		if($num_row >=1){echo "<table style='border:1px solid #666;padding:5px;background:#fff'><tr><th style='border:1px solid #666;padding:5px;background:#aaa'>#</th><th style='border:1px solid #666;padding:5px;background:#aaa'>Event</th><th style='border:1px solid #666;padding:5px;background:#aaa'>Lecturer</th><th style='border:1px solid #666;padding:5px;background:#aaa'>Category</th><th style='border:1px solid #666;padding:5px;background:#aaa'>Date</th><th style='border:1px solid #666;padding:5px;background:#aaa'>Time</th><th style='border:1px solid #666;padding:5px;background:#aaa'>Eligibility</th><th style='border:1px solid #666;padding:5px;background:#aaa'>Location</th><th style='border:1px solid #666;padding:5px;background:#aaa'>Venue</th></tr>";while($row = mysql_fetch_array($result)){$lecturer = new Lecturer();$user = new User();$lecturerData = $lecturer->getLecturerName($row['electurer']);$getsubject = $user->getSubjectName($row['ecategory_id']);$geteligibility = $user->getEligibleName($row['eligibility_id']);$getLocation = $user->getLocationName($row['elocation_id']);$getVenue = $user->getVenueName($row['evenue_no']);echo "<tr>";echo "<td style='border:1px solid #666;padding:5px;background:#fff'>".$row['id']."</td>";echo "<td style='border:1px solid #666;padding:5px;background:#fff'>".$row['ename']."</td>";echo "<td style='border:1px solid #666;padding:5px;background:#fff'>".$lecturerData->fname.' '.$lecturerData->lname."</td>";echo "<td style='border:1px solid #666;padding:5px;background:#fff'>".$getsubject->name."</td>";echo "<td style='border:1px solid #666;padding:5px;background:#fff'>".$row['edate']."</td>";echo "<td style='border:1px solid #666;padding:5px;background:#fff'>".$row['ehour'].":".$row['eminute']." ".$row['ehour_to'].":".$row['eminute_to']."</td>";echo "<td style='border:1px solid #666;padding:5px;background:#fff'>".$geteligibility->name."</td>";echo "<td style='border:1px solid #666;padding:5px;background:#fff'>".$getLocation->name."</td>";echo "<td style='border:1px solid #666;padding:5px;background:#fff'>".$getVenue->name."</td>";echo "</tr>";}echo "</table>";}else{echo "No Data.";}
	}	
}

//############# Lecturer & Subject & Eligibility Filter Details Start Here...
if (!empty($_POST['eLecturer']) && !empty($_POST['eSubject']) && !empty($_POST['eEligibility']) && empty($_POST['eLocation'])) {

	if (empty($_POST['fromdate']) && empty($_POST['todate'])) {
		
		$query = "SELECT * FROM `event` WHERE electurer = '".$_POST['eLecturer']."' and ecategory_id = '".$_POST['eSubject']."' and eligibility_id = '".$_POST['eEligibility']."' order by electurer";
		$result = mysql_query($query) or die(mysql_error());$num_row = mysql_num_rows($result);
		if($num_row >=1){echo "<table style='border:1px solid #666;padding:5px;background:#fff'><tr><th style='border:1px solid #666;padding:5px;background:#aaa'>#</th><th style='border:1px solid #666;padding:5px;background:#aaa'>Event</th><th style='border:1px solid #666;padding:5px;background:#aaa'>Lecturer</th><th style='border:1px solid #666;padding:5px;background:#aaa'>Category</th><th style='border:1px solid #666;padding:5px;background:#aaa'>Date</th><th style='border:1px solid #666;padding:5px;background:#aaa'>Time</th><th style='border:1px solid #666;padding:5px;background:#aaa'>Eligibility</th><th style='border:1px solid #666;padding:5px;background:#aaa'>Location</th><th style='border:1px solid #666;padding:5px;background:#aaa'>Venue</th></tr>";while($row = mysql_fetch_array($result)){$lecturer = new Lecturer();$user = new User();$lecturerData = $lecturer->getLecturerName($row['electurer']);$getsubject = $user->getSubjectName($row['ecategory_id']);$geteligibility = $user->getEligibleName($row['eligibility_id']);$getLocation = $user->getLocationName($row['elocation_id']);$getVenue = $user->getVenueName($row['evenue_no']);echo "<tr>";echo "<td style='border:1px solid #666;padding:5px;background:#fff'>".$row['id']."</td>";echo "<td style='border:1px solid #666;padding:5px;background:#fff'>".$row['ename']."</td>";echo "<td style='border:1px solid #666;padding:5px;background:#fff'>".$lecturerData->fname.' '.$lecturerData->lname."</td>";echo "<td style='border:1px solid #666;padding:5px;background:#fff'>".$getsubject->name."</td>";echo "<td style='border:1px solid #666;padding:5px;background:#fff'>".$row['edate']."</td>";echo "<td style='border:1px solid #666;padding:5px;background:#fff'>".$row['ehour'].":".$row['eminute']." ".$row['ehour_to'].":".$row['eminute_to']."</td>";echo "<td style='border:1px solid #666;padding:5px;background:#fff'>".$geteligibility->name."</td>";echo "<td style='border:1px solid #666;padding:5px;background:#fff'>".$getLocation->name."</td>";echo "<td style='border:1px solid #666;padding:5px;background:#fff'>".$getVenue->name."</td>";echo "</tr>";}echo "</table>";}else{echo "No Data.";}
	}
	else{

		$query = "SELECT * FROM `event` WHERE electurer = '".$_POST['eLecturer']."' and ecategory_id = '".$_POST['eSubject']."' and eligibility_id = '".$_POST['eEligibility']."' and edate between '".$_POST['fromdate']."' and '".$_POST['todate']."' order by edate";		
		$result = mysql_query($query) or die(mysql_error());$num_row = mysql_num_rows($result);
		if($num_row >=1){echo "<table style='border:1px solid #666;padding:5px;background:#fff'><tr><th style='border:1px solid #666;padding:5px;background:#aaa'>#</th><th style='border:1px solid #666;padding:5px;background:#aaa'>Event</th><th style='border:1px solid #666;padding:5px;background:#aaa'>Lecturer</th><th style='border:1px solid #666;padding:5px;background:#aaa'>Category</th><th style='border:1px solid #666;padding:5px;background:#aaa'>Date</th><th style='border:1px solid #666;padding:5px;background:#aaa'>Time</th><th style='border:1px solid #666;padding:5px;background:#aaa'>Eligibility</th><th style='border:1px solid #666;padding:5px;background:#aaa'>Location</th><th style='border:1px solid #666;padding:5px;background:#aaa'>Venue</th></tr>";while($row = mysql_fetch_array($result)){$lecturer = new Lecturer();$user = new User();$lecturerData = $lecturer->getLecturerName($row['electurer']);$getsubject = $user->getSubjectName($row['ecategory_id']);$geteligibility = $user->getEligibleName($row['eligibility_id']);$getLocation = $user->getLocationName($row['elocation_id']);$getVenue = $user->getVenueName($row['evenue_no']);echo "<tr>";echo "<td style='border:1px solid #666;padding:5px;background:#fff'>".$row['id']."</td>";echo "<td style='border:1px solid #666;padding:5px;background:#fff'>".$row['ename']."</td>";echo "<td style='border:1px solid #666;padding:5px;background:#fff'>".$lecturerData->fname.' '.$lecturerData->lname."</td>";echo "<td style='border:1px solid #666;padding:5px;background:#fff'>".$getsubject->name."</td>";echo "<td style='border:1px solid #666;padding:5px;background:#fff'>".$row['edate']."</td>";echo "<td style='border:1px solid #666;padding:5px;background:#fff'>".$row['ehour'].":".$row['eminute']." ".$row['ehour_to'].":".$row['eminute_to']."</td>";echo "<td style='border:1px solid #666;padding:5px;background:#fff'>".$geteligibility->name."</td>";echo "<td style='border:1px solid #666;padding:5px;background:#fff'>".$getLocation->name."</td>";echo "<td style='border:1px solid #666;padding:5px;background:#fff'>".$getVenue->name."</td>";echo "</tr>";}echo "</table>";}else{echo "No Data.";}
	}	
}

//############# Lecturer & Eligibility & Location Filter Details Start Here...
if (!empty($_POST['eLecturer']) && empty($_POST['eSubject']) && !empty($_POST['eEligibility']) && !empty($_POST['eLocation'])) {

	if (empty($_POST['fromdate']) && empty($_POST['todate'])) {
		
		$query = "SELECT * FROM `event` WHERE electurer = '".$_POST['eLecturer']."' and elocation_id = '".$_POST['eLocation']."' and eligibility_id = '".$_POST['eEligibility']."' order by electurer";
		$result = mysql_query($query) or die(mysql_error());$num_row = mysql_num_rows($result);
		if($num_row >=1){echo "<table style='border:1px solid #666;padding:5px;background:#fff'><tr><th style='border:1px solid #666;padding:5px;background:#aaa'>#</th><th style='border:1px solid #666;padding:5px;background:#aaa'>Event</th><th style='border:1px solid #666;padding:5px;background:#aaa'>Lecturer</th><th style='border:1px solid #666;padding:5px;background:#aaa'>Category</th><th style='border:1px solid #666;padding:5px;background:#aaa'>Date</th><th style='border:1px solid #666;padding:5px;background:#aaa'>Time</th><th style='border:1px solid #666;padding:5px;background:#aaa'>Eligibility</th><th style='border:1px solid #666;padding:5px;background:#aaa'>Location</th><th style='border:1px solid #666;padding:5px;background:#aaa'>Venue</th></tr>";while($row = mysql_fetch_array($result)){$lecturer = new Lecturer();$user = new User();$lecturerData = $lecturer->getLecturerName($row['electurer']);$getsubject = $user->getSubjectName($row['ecategory_id']);$geteligibility = $user->getEligibleName($row['eligibility_id']);$getLocation = $user->getLocationName($row['elocation_id']);$getVenue = $user->getVenueName($row['evenue_no']);echo "<tr>";echo "<td style='border:1px solid #666;padding:5px;background:#fff'>".$row['id']."</td>";echo "<td style='border:1px solid #666;padding:5px;background:#fff'>".$row['ename']."</td>";echo "<td style='border:1px solid #666;padding:5px;background:#fff'>".$lecturerData->fname.' '.$lecturerData->lname."</td>";echo "<td style='border:1px solid #666;padding:5px;background:#fff'>".$getsubject->name."</td>";echo "<td style='border:1px solid #666;padding:5px;background:#fff'>".$row['edate']."</td>";echo "<td style='border:1px solid #666;padding:5px;background:#fff'>".$row['ehour'].":".$row['eminute']." ".$row['ehour_to'].":".$row['eminute_to']."</td>";echo "<td style='border:1px solid #666;padding:5px;background:#fff'>".$geteligibility->name."</td>";echo "<td style='border:1px solid #666;padding:5px;background:#fff'>".$getLocation->name."</td>";echo "<td style='border:1px solid #666;padding:5px;background:#fff'>".$getVenue->name."</td>";echo "</tr>";}echo "</table>";}else{echo "No Data.";}
	}
	else{

		$query = "SELECT * FROM `event` WHERE electurer = '".$_POST['eLecturer']."' and elocation_id = '".$_POST['eLocation']."' and eligibility_id = '".$_POST['eEligibility']."' and edate between '".$_POST['fromdate']."' and '".$_POST['todate']."' order by edate";		
		$result = mysql_query($query) or die(mysql_error());$num_row = mysql_num_rows($result);
		if($num_row >=1){echo "<table style='border:1px solid #666;padding:5px;background:#fff'><tr><th style='border:1px solid #666;padding:5px;background:#aaa'>#</th><th style='border:1px solid #666;padding:5px;background:#aaa'>Event</th><th style='border:1px solid #666;padding:5px;background:#aaa'>Lecturer</th><th style='border:1px solid #666;padding:5px;background:#aaa'>Category</th><th style='border:1px solid #666;padding:5px;background:#aaa'>Date</th><th style='border:1px solid #666;padding:5px;background:#aaa'>Time</th><th style='border:1px solid #666;padding:5px;background:#aaa'>Eligibility</th><th style='border:1px solid #666;padding:5px;background:#aaa'>Location</th><th style='border:1px solid #666;padding:5px;background:#aaa'>Venue</th></tr>";while($row = mysql_fetch_array($result)){$lecturer = new Lecturer();$user = new User();$lecturerData = $lecturer->getLecturerName($row['electurer']);$getsubject = $user->getSubjectName($row['ecategory_id']);$geteligibility = $user->getEligibleName($row['eligibility_id']);$getLocation = $user->getLocationName($row['elocation_id']);$getVenue = $user->getVenueName($row['evenue_no']);echo "<tr>";echo "<td style='border:1px solid #666;padding:5px;background:#fff'>".$row['id']."</td>";echo "<td style='border:1px solid #666;padding:5px;background:#fff'>".$row['ename']."</td>";echo "<td style='border:1px solid #666;padding:5px;background:#fff'>".$lecturerData->fname.' '.$lecturerData->lname."</td>";echo "<td style='border:1px solid #666;padding:5px;background:#fff'>".$getsubject->name."</td>";echo "<td style='border:1px solid #666;padding:5px;background:#fff'>".$row['edate']."</td>";echo "<td style='border:1px solid #666;padding:5px;background:#fff'>".$row['ehour'].":".$row['eminute']." ".$row['ehour_to'].":".$row['eminute_to']."</td>";echo "<td style='border:1px solid #666;padding:5px;background:#fff'>".$geteligibility->name."</td>";echo "<td style='border:1px solid #666;padding:5px;background:#fff'>".$getLocation->name."</td>";echo "<td style='border:1px solid #666;padding:5px;background:#fff'>".$getVenue->name."</td>";echo "</tr>";}echo "</table>";}else{echo "No Data.";}
	}	
}

//############# Subject & Eligibility & Location Filter Details Start Here...
if (empty($_POST['eLecturer']) && !empty($_POST['eSubject']) && !empty($_POST['eEligibility']) && !empty($_POST['eLocation'])) {

	if (empty($_POST['fromdate']) && empty($_POST['todate'])) {
		
		$query = "SELECT * FROM `event` WHERE ecategory_id = '".$_POST['eSubject']."' and elocation_id = '".$_POST['eLocation']."' and eligibility_id = '".$_POST['eEligibility']."' order by electurer";
		$result = mysql_query($query) or die(mysql_error());$num_row = mysql_num_rows($result);
		if($num_row >=1){echo "<table style='border:1px solid #666;padding:5px;background:#fff'><tr><th style='border:1px solid #666;padding:5px;background:#aaa'>#</th><th style='border:1px solid #666;padding:5px;background:#aaa'>Event</th><th style='border:1px solid #666;padding:5px;background:#aaa'>Lecturer</th><th style='border:1px solid #666;padding:5px;background:#aaa'>Category</th><th style='border:1px solid #666;padding:5px;background:#aaa'>Date</th><th style='border:1px solid #666;padding:5px;background:#aaa'>Time</th><th style='border:1px solid #666;padding:5px;background:#aaa'>Eligibility</th><th style='border:1px solid #666;padding:5px;background:#aaa'>Location</th><th style='border:1px solid #666;padding:5px;background:#aaa'>Venue</th></tr>";while($row = mysql_fetch_array($result)){$lecturer = new Lecturer();$user = new User();$lecturerData = $lecturer->getLecturerName($row['electurer']);$getsubject = $user->getSubjectName($row['ecategory_id']);$geteligibility = $user->getEligibleName($row['eligibility_id']);$getLocation = $user->getLocationName($row['elocation_id']);$getVenue = $user->getVenueName($row['evenue_no']);echo "<tr>";echo "<td style='border:1px solid #666;padding:5px;background:#fff'>".$row['id']."</td>";echo "<td style='border:1px solid #666;padding:5px;background:#fff'>".$row['ename']."</td>";echo "<td style='border:1px solid #666;padding:5px;background:#fff'>".$lecturerData->fname.' '.$lecturerData->lname."</td>";echo "<td style='border:1px solid #666;padding:5px;background:#fff'>".$getsubject->name."</td>";echo "<td style='border:1px solid #666;padding:5px;background:#fff'>".$row['edate']."</td>";echo "<td style='border:1px solid #666;padding:5px;background:#fff'>".$row['ehour'].":".$row['eminute']." ".$row['ehour_to'].":".$row['eminute_to']."</td>";echo "<td style='border:1px solid #666;padding:5px;background:#fff'>".$geteligibility->name."</td>";echo "<td style='border:1px solid #666;padding:5px;background:#fff'>".$getLocation->name."</td>";echo "<td style='border:1px solid #666;padding:5px;background:#fff'>".$getVenue->name."</td>";echo "</tr>";}echo "</table>";}else{echo "No Data.";}
	}
	else{

		$query = "SELECT * FROM `event` WHERE ecategory_id = '".$_POST['eSubject']."' and elocation_id = '".$_POST['eLocation']."' and eligibility_id = '".$_POST['eEligibility']."' and edate between '".$_POST['fromdate']."' and '".$_POST['todate']."' order by edate";		
		$result = mysql_query($query) or die(mysql_error());$num_row = mysql_num_rows($result);
		if($num_row >=1){echo "<table style='border:1px solid #666;padding:5px;background:#fff'><tr><th style='border:1px solid #666;padding:5px;background:#aaa'>#</th><th style='border:1px solid #666;padding:5px;background:#aaa'>Event</th><th style='border:1px solid #666;padding:5px;background:#aaa'>Lecturer</th><th style='border:1px solid #666;padding:5px;background:#aaa'>Category</th><th style='border:1px solid #666;padding:5px;background:#aaa'>Date</th><th style='border:1px solid #666;padding:5px;background:#aaa'>Time</th><th style='border:1px solid #666;padding:5px;background:#aaa'>Eligibility</th><th style='border:1px solid #666;padding:5px;background:#aaa'>Location</th><th style='border:1px solid #666;padding:5px;background:#aaa'>Venue</th></tr>";while($row = mysql_fetch_array($result)){$lecturer = new Lecturer();$user = new User();$lecturerData = $lecturer->getLecturerName($row['electurer']);$getsubject = $user->getSubjectName($row['ecategory_id']);$geteligibility = $user->getEligibleName($row['eligibility_id']);$getLocation = $user->getLocationName($row['elocation_id']);$getVenue = $user->getVenueName($row['evenue_no']);echo "<tr>";echo "<td style='border:1px solid #666;padding:5px;background:#fff'>".$row['id']."</td>";echo "<td style='border:1px solid #666;padding:5px;background:#fff'>".$row['ename']."</td>";echo "<td style='border:1px solid #666;padding:5px;background:#fff'>".$lecturerData->fname.' '.$lecturerData->lname."</td>";echo "<td style='border:1px solid #666;padding:5px;background:#fff'>".$getsubject->name."</td>";echo "<td style='border:1px solid #666;padding:5px;background:#fff'>".$row['edate']."</td>";echo "<td style='border:1px solid #666;padding:5px;background:#fff'>".$row['ehour'].":".$row['eminute']." ".$row['ehour_to'].":".$row['eminute_to']."</td>";echo "<td style='border:1px solid #666;padding:5px;background:#fff'>".$geteligibility->name."</td>";echo "<td style='border:1px solid #666;padding:5px;background:#fff'>".$getLocation->name."</td>";echo "<td style='border:1px solid #666;padding:5px;background:#fff'>".$getVenue->name."</td>";echo "</tr>";}echo "</table>";}else{echo "No Data.";}
	}	
}

//############# Lecturer & Subject & Location Filter Details Start Here...
if (!empty($_POST['eLecturer']) && !empty($_POST['eSubject']) && empty($_POST['eEligibility']) && !empty($_POST['eLocation'])) {

	if (empty($_POST['fromdate']) && empty($_POST['todate'])) {
		
		$query = "SELECT * FROM `event` WHERE ecategory_id = '".$_POST['eSubject']."' and elocation_id = '".$_POST['eLocation']."' and electurer = '".$_POST['eLecturer']."' order by electurer";
		$result = mysql_query($query) or die(mysql_error());$num_row = mysql_num_rows($result);
		if($num_row >=1){echo "<table style='border:1px solid #666;padding:5px;background:#fff'><tr><th style='border:1px solid #666;padding:5px;background:#aaa'>#</th><th style='border:1px solid #666;padding:5px;background:#aaa'>Event</th><th style='border:1px solid #666;padding:5px;background:#aaa'>Lecturer</th><th style='border:1px solid #666;padding:5px;background:#aaa'>Category</th><th style='border:1px solid #666;padding:5px;background:#aaa'>Date</th><th style='border:1px solid #666;padding:5px;background:#aaa'>Time</th><th style='border:1px solid #666;padding:5px;background:#aaa'>Eligibility</th><th style='border:1px solid #666;padding:5px;background:#aaa'>Location</th><th style='border:1px solid #666;padding:5px;background:#aaa'>Venue</th></tr>";while($row = mysql_fetch_array($result)){$lecturer = new Lecturer();$user = new User();$lecturerData = $lecturer->getLecturerName($row['electurer']);$getsubject = $user->getSubjectName($row['ecategory_id']);$geteligibility = $user->getEligibleName($row['eligibility_id']);$getLocation = $user->getLocationName($row['elocation_id']);$getVenue = $user->getVenueName($row['evenue_no']);echo "<tr>";echo "<td style='border:1px solid #666;padding:5px;background:#fff'>".$row['id']."</td>";echo "<td style='border:1px solid #666;padding:5px;background:#fff'>".$row['ename']."</td>";echo "<td style='border:1px solid #666;padding:5px;background:#fff'>".$lecturerData->fname.' '.$lecturerData->lname."</td>";echo "<td style='border:1px solid #666;padding:5px;background:#fff'>".$getsubject->name."</td>";echo "<td style='border:1px solid #666;padding:5px;background:#fff'>".$row['edate']."</td>";echo "<td style='border:1px solid #666;padding:5px;background:#fff'>".$row['ehour'].":".$row['eminute']." ".$row['ehour_to'].":".$row['eminute_to']."</td>";echo "<td style='border:1px solid #666;padding:5px;background:#fff'>".$geteligibility->name."</td>";echo "<td style='border:1px solid #666;padding:5px;background:#fff'>".$getLocation->name."</td>";echo "<td style='border:1px solid #666;padding:5px;background:#fff'>".$getVenue->name."</td>";echo "</tr>";}echo "</table>";}else{echo "No Data.";}
	}
	else{

		$query = "SELECT * FROM `event` WHERE ecategory_id = '".$_POST['eSubject']."' and elocation_id = '".$_POST['eLocation']."' and electurer = '".$_POST['eLecturer']."' and edate between '".$_POST['fromdate']."' and '".$_POST['todate']."' order by edate";		
		$result = mysql_query($query) or die(mysql_error());$num_row = mysql_num_rows($result);
		if($num_row >=1){echo "<table style='border:1px solid #666;padding:5px;background:#fff'><tr><th style='border:1px solid #666;padding:5px;background:#aaa'>#</th><th style='border:1px solid #666;padding:5px;background:#aaa'>Event</th><th style='border:1px solid #666;padding:5px;background:#aaa'>Lecturer</th><th style='border:1px solid #666;padding:5px;background:#aaa'>Category</th><th style='border:1px solid #666;padding:5px;background:#aaa'>Date</th><th style='border:1px solid #666;padding:5px;background:#aaa'>Time</th><th style='border:1px solid #666;padding:5px;background:#aaa'>Eligibility</th><th style='border:1px solid #666;padding:5px;background:#aaa'>Location</th><th style='border:1px solid #666;padding:5px;background:#aaa'>Venue</th></tr>";while($row = mysql_fetch_array($result)){$lecturer = new Lecturer();$user = new User();$lecturerData = $lecturer->getLecturerName($row['electurer']);$getsubject = $user->getSubjectName($row['ecategory_id']);$geteligibility = $user->getEligibleName($row['eligibility_id']);$getLocation = $user->getLocationName($row['elocation_id']);$getVenue = $user->getVenueName($row['evenue_no']);echo "<tr>";echo "<td style='border:1px solid #666;padding:5px;background:#fff'>".$row['id']."</td>";echo "<td style='border:1px solid #666;padding:5px;background:#fff'>".$row['ename']."</td>";echo "<td style='border:1px solid #666;padding:5px;background:#fff'>".$lecturerData->fname.' '.$lecturerData->lname."</td>";echo "<td style='border:1px solid #666;padding:5px;background:#fff'>".$getsubject->name."</td>";echo "<td style='border:1px solid #666;padding:5px;background:#fff'>".$row['edate']."</td>";echo "<td style='border:1px solid #666;padding:5px;background:#fff'>".$row['ehour'].":".$row['eminute']." ".$row['ehour_to'].":".$row['eminute_to']."</td>";echo "<td style='border:1px solid #666;padding:5px;background:#fff'>".$geteligibility->name."</td>";echo "<td style='border:1px solid #666;padding:5px;background:#fff'>".$getLocation->name."</td>";echo "<td style='border:1px solid #666;padding:5px;background:#fff'>".$getVenue->name."</td>";echo "</tr>";}echo "</table>";}else{echo "No Data.";}
	}	
}

//############# Lecturer & Subject & Eligibility & Location Filter Details Start Here...
if (!empty($_POST['eLecturer']) && !empty($_POST['eSubject']) && !empty($_POST['eEligibility']) && !empty($_POST['eLocation'])) {

	if (empty($_POST['fromdate']) && empty($_POST['todate'])) {
		
		$query = "SELECT * FROM `event` WHERE ecategory_id = '".$_POST['eSubject']."' and elocation_id = '".$_POST['eLocation']."' and electurer = '".$_POST['eLecturer']."' and eligibility_id = '".$_POST['eEligibility']."' order by electurer";
		$result = mysql_query($query) or die(mysql_error());$num_row = mysql_num_rows($result);
		if($num_row >=1){echo "<table style='border:1px solid #666;padding:5px;background:#fff'><tr><th style='border:1px solid #666;padding:5px;background:#aaa'>#</th><th style='border:1px solid #666;padding:5px;background:#aaa'>Event</th><th style='border:1px solid #666;padding:5px;background:#aaa'>Lecturer</th><th style='border:1px solid #666;padding:5px;background:#aaa'>Category</th><th style='border:1px solid #666;padding:5px;background:#aaa'>Date</th><th style='border:1px solid #666;padding:5px;background:#aaa'>Time</th><th style='border:1px solid #666;padding:5px;background:#aaa'>Eligibility</th><th style='border:1px solid #666;padding:5px;background:#aaa'>Location</th><th style='border:1px solid #666;padding:5px;background:#aaa'>Venue</th></tr>";while($row = mysql_fetch_array($result)){$lecturer = new Lecturer();$user = new User();$lecturerData = $lecturer->getLecturerName($row['electurer']);$getsubject = $user->getSubjectName($row['ecategory_id']);$geteligibility = $user->getEligibleName($row['eligibility_id']);$getLocation = $user->getLocationName($row['elocation_id']);$getVenue = $user->getVenueName($row['evenue_no']);echo "<tr>";echo "<td style='border:1px solid #666;padding:5px;background:#fff'>".$row['id']."</td>";echo "<td style='border:1px solid #666;padding:5px;background:#fff'>".$row['ename']."</td>";echo "<td style='border:1px solid #666;padding:5px;background:#fff'>".$lecturerData->fname.' '.$lecturerData->lname."</td>";echo "<td style='border:1px solid #666;padding:5px;background:#fff'>".$getsubject->name."</td>";echo "<td style='border:1px solid #666;padding:5px;background:#fff'>".$row['edate']."</td>";echo "<td style='border:1px solid #666;padding:5px;background:#fff'>".$row['ehour'].":".$row['eminute']." ".$row['ehour_to'].":".$row['eminute_to']."</td>";echo "<td style='border:1px solid #666;padding:5px;background:#fff'>".$geteligibility->name."</td>";echo "<td style='border:1px solid #666;padding:5px;background:#fff'>".$getLocation->name."</td>";echo "<td style='border:1px solid #666;padding:5px;background:#fff'>".$getVenue->name."</td>";echo "</tr>";}echo "</table>";}else{echo "No Data.";}
	}
	else{

		$query = "SELECT * FROM `event` WHERE ecategory_id = '".$_POST['eSubject']."' and elocation_id = '".$_POST['eLocation']."' and electurer = '".$_POST['eLecturer']."' and eligibility_id = '".$_POST['eEligibility']."' and edate between '".$_POST['fromdate']."' and '".$_POST['todate']."' order by edate";		
		$result = mysql_query($query) or die(mysql_error());$num_row = mysql_num_rows($result);
		if($num_row >=1){echo "<table style='border:1px solid #666;padding:5px;background:#fff'><tr><th style='border:1px solid #666;padding:5px;background:#aaa'>#</th><th style='border:1px solid #666;padding:5px;background:#aaa'>Event</th><th style='border:1px solid #666;padding:5px;background:#aaa'>Lecturer</th><th style='border:1px solid #666;padding:5px;background:#aaa'>Category</th><th style='border:1px solid #666;padding:5px;background:#aaa'>Date</th><th style='border:1px solid #666;padding:5px;background:#aaa'>Time</th><th style='border:1px solid #666;padding:5px;background:#aaa'>Eligibility</th><th style='border:1px solid #666;padding:5px;background:#aaa'>Location</th><th style='border:1px solid #666;padding:5px;background:#aaa'>Venue</th></tr>";while($row = mysql_fetch_array($result)){$lecturer = new Lecturer();$user = new User();$lecturerData = $lecturer->getLecturerName($row['electurer']);$getsubject = $user->getSubjectName($row['ecategory_id']);$geteligibility = $user->getEligibleName($row['eligibility_id']);$getLocation = $user->getLocationName($row['elocation_id']);$getVenue = $user->getVenueName($row['evenue_no']);echo "<tr>";echo "<td style='border:1px solid #666;padding:5px;background:#fff'>".$row['id']."</td>";echo "<td style='border:1px solid #666;padding:5px;background:#fff'>".$row['ename']."</td>";echo "<td style='border:1px solid #666;padding:5px;background:#fff'>".$lecturerData->fname.' '.$lecturerData->lname."</td>";echo "<td style='border:1px solid #666;padding:5px;background:#fff'>".$getsubject->name."</td>";echo "<td style='border:1px solid #666;padding:5px;background:#fff'>".$row['edate']."</td>";echo "<td style='border:1px solid #666;padding:5px;background:#fff'>".$row['ehour'].":".$row['eminute']." ".$row['ehour_to'].":".$row['eminute_to']."</td>";echo "<td style='border:1px solid #666;padding:5px;background:#fff'>".$geteligibility->name."</td>";echo "<td style='border:1px solid #666;padding:5px;background:#fff'>".$getLocation->name."</td>";echo "<td style='border:1px solid #666;padding:5px;background:#fff'>".$getVenue->name."</td>";echo "</tr>";}echo "</table>";}else{echo "No Data.";}
	}	
}

//############# All Event Filter Details Start Here...
if (!empty($_POST['allEvent'])) {

	if (empty($_POST['fromdate']) && empty($_POST['todate'])) {
		
		$query = "SELECT * FROM `event` order by edate";
		$result = mysql_query($query) or die(mysql_error());$num_row = mysql_num_rows($result);
		if($num_row >=1){echo "<table style='border:1px solid #666;padding:5px;background:#fff'><tr><th style='border:1px solid #666;padding:5px;background:#aaa'>#</th><th style='border:1px solid #666;padding:5px;background:#aaa'>Event</th><th style='border:1px solid #666;padding:5px;background:#aaa'>Lecturer</th><th style='border:1px solid #666;padding:5px;background:#aaa'>Category</th><th style='border:1px solid #666;padding:5px;background:#aaa'>Date</th><th style='border:1px solid #666;padding:5px;background:#aaa'>Time</th><th style='border:1px solid #666;padding:5px;background:#aaa'>Eligibility</th><th style='border:1px solid #666;padding:5px;background:#aaa'>Location</th><th style='border:1px solid #666;padding:5px;background:#aaa'>Venue</th></tr>";while($row = mysql_fetch_array($result)){$lecturer = new Lecturer();$user = new User();$lecturerData = $lecturer->getLecturerName($row['electurer']);$getsubject = $user->getSubjectName($row['ecategory_id']);$geteligibility = $user->getEligibleName($row['eligibility_id']);$getLocation = $user->getLocationName($row['elocation_id']);$getVenue = $user->getVenueName($row['evenue_no']);echo "<tr>";echo "<td style='border:1px solid #666;padding:5px;background:#fff'>".$row['id']."</td>";echo "<td style='border:1px solid #666;padding:5px;background:#fff'>".$row['ename']."</td>";echo "<td style='border:1px solid #666;padding:5px;background:#fff'>".$lecturerData->fname.' '.$lecturerData->lname."</td>";echo "<td style='border:1px solid #666;padding:5px;background:#fff'>".$getsubject->name."</td>";echo "<td style='border:1px solid #666;padding:5px;background:#fff'>".$row['edate']."</td>";echo "<td style='border:1px solid #666;padding:5px;background:#fff'>".$row['ehour'].":".$row['eminute']." ".$row['ehour_to'].":".$row['eminute_to']."</td>";echo "<td style='border:1px solid #666;padding:5px;background:#fff'>".$geteligibility->name."</td>";echo "<td style='border:1px solid #666;padding:5px;background:#fff'>".$getLocation->name."</td>";echo "<td style='border:1px solid #666;padding:5px;background:#fff'>".$getVenue->name."</td>";echo "</tr>";}echo "</table>";}else{echo "No Data.";}
	}
	else{

		$query = "SELECT * FROM `event` WHERE edate between '".$_POST['fromdate']."' and '".$_POST['todate']."' order by edate";		
		$result = mysql_query($query) or die(mysql_error());$num_row = mysql_num_rows($result);
		if($num_row >=1){echo "<table style='border:1px solid #666;padding:5px;background:#fff'><tr><th style='border:1px solid #666;padding:5px;background:#aaa'>#</th><th style='border:1px solid #666;padding:5px;background:#aaa'>Event</th><th style='border:1px solid #666;padding:5px;background:#aaa'>Lecturer</th><th style='border:1px solid #666;padding:5px;background:#aaa'>Category</th><th style='border:1px solid #666;padding:5px;background:#aaa'>Date</th><th style='border:1px solid #666;padding:5px;background:#aaa'>Time</th><th style='border:1px solid #666;padding:5px;background:#aaa'>Eligibility</th><th style='border:1px solid #666;padding:5px;background:#aaa'>Location</th><th style='border:1px solid #666;padding:5px;background:#aaa'>Venue</th></tr>";while($row = mysql_fetch_array($result)){$lecturer = new Lecturer();$user = new User();$lecturerData = $lecturer->getLecturerName($row['electurer']);$getsubject = $user->getSubjectName($row['ecategory_id']);$geteligibility = $user->getEligibleName($row['eligibility_id']);$getLocation = $user->getLocationName($row['elocation_id']);$getVenue = $user->getVenueName($row['evenue_no']);echo "<tr>";echo "<td style='border:1px solid #666;padding:5px;background:#fff'>".$row['id']."</td>";echo "<td style='border:1px solid #666;padding:5px;background:#fff'>".$row['ename']."</td>";echo "<td style='border:1px solid #666;padding:5px;background:#fff'>".$lecturerData->fname.' '.$lecturerData->lname."</td>";echo "<td style='border:1px solid #666;padding:5px;background:#fff'>".$getsubject->name."</td>";echo "<td style='border:1px solid #666;padding:5px;background:#fff'>".$row['edate']."</td>";echo "<td style='border:1px solid #666;padding:5px;background:#fff'>".$row['ehour'].":".$row['eminute']." ".$row['ehour_to'].":".$row['eminute_to']."</td>";echo "<td style='border:1px solid #666;padding:5px;background:#fff'>".$geteligibility->name."</td>";echo "<td style='border:1px solid #666;padding:5px;background:#fff'>".$getLocation->name."</td>";echo "<td style='border:1px solid #666;padding:5px;background:#fff'>".$getVenue->name."</td>";echo "</tr>";}echo "</table>";}else{echo "No Data.";}
	}	
}

?>
